### PR TITLE
use argparse so you can test arbitrary log sources and patterns

### PR DESCRIPTION
**Pull request by ckuethe**
This way you can
`./run_korg.py -l /var/log/auth.log -g '%{SUDO}' -p ~/logstash/local-patterns/`

and get something like
`{u'sudo_command': '/usr/bin/apt update', u'sudo_pwd': '/home/ckuethe', u'sudo_tty': 'pts/0', u'sudo_message': None, u'sudo_reason': None, u'sudo_runas': 'root', u'sudo_user': 'ckuethe'}`

If you're developing a `sudo` pattern, for example...

### CODE REVIEW

**Comment by markfink** [comment]
you probably did not know: I do not accept any pull-request without tests

**Comment by ckuethe** [comment]
I'll let you figure out how to build a test harness for run_korg...

```
head /var/log/syslog  | ./run_korg.py -g '%{SYSLOGBASE} %{GREEDYDATA:message}' -f logsource program message
```

does what you'd expect, eg.

```
{'message': 'Device: /dev/sda [SAT], SMART Usage Attribute: 194 Temperature_Celsius changed from 31 to 32', 'program': 'smartd', 'logsource': 'yoga900'}
{'message': 'DHCPREQUEST of 192.168.1.10 on wlp1s0 to 192.168.1.2 port 67 (xid=0x538a46d2)', 'program': 'dhclient', 'logsource': 'yoga900'}
{'message': 'DHCPACK of 192.168.1.10 from 192.168.1.2', 'program': 'dhclient', 'logsource': 'yoga900'}
{'message': 'bound to 192.168.1.10 -- renewal in 1573 seconds.', 'program': 'dhclient', 'logsource': 'yoga900'}
{'message': 'interface 2 does not have a name or an address, skip', 'program': 'lldpd', 'logsource': 'yoga900'}
{'message': '[origin software="rsyslogd" swVersion="8.16.0" x-pid="968" x-info="http://www.rsyslog.com"] rsyslogd was HUPed', 'program': 'rsyslogd', 'logsource': 'yoga900'}
{'message': 'pam_ecryptfs: pam_sm_authenticate: /home/ckuethe is already mounted', 'program': 'lightdm', 'logsource': 'yoga900'}
{'message': 'nl80211: send_and_recv->nl_recvmsgs failed: -33', 'program': 'wpa_supplicant', 'logsource': 'yoga900'}

```

**Comment by markfink** [comment]
fair enough but it must wait till I have more time

**Comment by markfink** [comment]
I removed the run_korg.py script to make it explicit that this is not a command line tool but a lib.

**Pull request closed without merging**
